import type { Metadata } from 'next'
import '../styles/globals.css'
import '../styles/theme.css'

export const metadata: Metadata = {
  title: '抖音 APP ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
